# Generated by Django 5.0.4 on 2024-04-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_journal', '0002_exam_test_url_userprofile_remove_attendance_present_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
