# Generated by Django 5.0.4 on 2024-04-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_journal', '0004_parent_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_journal.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(to='school_journal.lesson'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_journal.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_journal.student'),
        ),
    ]
