# Generated by Django 4.2.11 on 2024-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_journal", "0005_lesson_teacher_student_lessons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="lessons",
            field=models.ManyToManyField(
                null=True, related_name="students", to="school_journal.lesson"
            ),
        ),
    ]
