# Generated by Django 4.2.11 on 2024-04-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_journal",
            "0006_alter_exam_id_alter_grade_id_alter_lesson_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="grade", name="lesson",),
        migrations.AddField(
            model_name="grade",
            name="exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.exam",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="test",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.test",
            ),
        ),
    ]
