# Generated by Django 4.2.11 on 2024-04-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school_journal", "0007_remove_grade_lesson_grade_exam_grade_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.exam",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.test",
            ),
        ),
    ]
