# Generated by Django 4.2.11 on 2024-04-09 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("school_journal", "0008_alter_grade_exam_alter_grade_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="exam", name="date",),
        migrations.RemoveField(model_name="test", name="date",),
        migrations.AddField(
            model_name="exam",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="test",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
