# Generated by Django 4.2.11 on 2024-04-09 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_journal",
            "0009_remove_exam_date_remove_test_date_exam_date_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="admin", new_name="parent",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
