# Generated by Django 4.2.11 on 2024-04-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school_journal", "0010_rename_admin_student_parent_alter_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="attendance", name="date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_journal.parent",
            ),
        ),
    ]
